module.exports = [
  { id:'sword', name:'سيف', category:'weapons', difficulty:'easy', aliases:['سيف','سلاح'] },
  { id:'bow', name:'قوس', category:'weapons', difficulty:'easy', aliases:['قوس'] },
  { id:'shield', name:'درع', category:'weapons', difficulty:'easy', aliases:['درع'] },
  { id:'axe', name:'فأس', category:'weapons', difficulty:'easy', aliases:['فأس','فاس'] },
  { id:'spear', name:'رمح', category:'weapons', difficulty:'medium', aliases:['رمح'] },
  { id:'dagger', name:'خنجر', category:'weapons', difficulty:'medium', aliases:['خنجر'] },
  { id:'cat', name:'قط', category:'animals', difficulty:'easy', aliases:['قط','قطة'] },
  { id:'dog', name:'كلب', category:'animals', difficulty:'easy', aliases:['كلب'] },
  { id:'lion', name:'أسد', category:'animals', difficulty:'easy', aliases:['أسد'] },
  { id:'elephant', name:'فيل', category:'animals', difficulty:'easy', aliases:['فيل'] },
  { id:'eagle', name:'نسر', category:'animals', difficulty:'medium', aliases:['نسر'] },
  { id:'snake', name:'أفعى', category:'animals', difficulty:'easy', aliases:['أفعى','حية'] },
  { id:'horse', name:'حصان', category:'animals', difficulty:'easy', aliases:['حصان'] },
  { id:'apple', name:'تفاحة', category:'food', difficulty:'easy', aliases:['تفاحة','تفاح'] },
  { id:'banana', name:'موز', category:'food', difficulty:'easy', aliases:['موز'] },
  { id:'pizza', name:'بيتزا', category:'food', difficulty:'easy', aliases:['بيتزا'] },
  { id:'coffee', name:'قهوة', category:'food', difficulty:'easy', aliases:['قهوة'] },
  { id:'bread', name:'خبز', category:'food', difficulty:'easy', aliases:['خبز'] },
  { id:'chocolate', name:'شوكولاتة', category:'food', difficulty:'easy', aliases:['شوكولاتة'] },
  { id:'hammer', name:'مطرقة', category:'tools', difficulty:'easy', aliases:['مطرقة'] },
  { id:'screwdriver', name:'مفك', category:'tools', difficulty:'easy', aliases:['مفك'] },
  { id:'saw', name:'منشار', category:'tools', difficulty:'easy', aliases:['منشار'] },
  { id:'drill', name:'مثقاب', category:'tools', difficulty:'medium', aliases:['مثقاب'] },
  { id:'chair', name:'كرسي', category:'household', difficulty:'easy', aliases:['كرسي'] },
  { id:'table', name:'طاولة', category:'household', difficulty:'easy', aliases:['طاولة'] },
  { id:'lamp', name:'مصباح', category:'household', difficulty:'easy', aliases:['مصباح'] },
  { id:'mirror', name:'مرآة', category:'household', difficulty:'easy', aliases:['مرآة'] },
  { id:'phone', name:'هاتف', category:'electronics', difficulty:'easy', aliases:['هاتف','جوال'] },
  { id:'computer', name:'حاسوب', category:'electronics', difficulty:'easy', aliases:['حاسوب','كمبيوتر'] },
  { id:'camera', name:'كاميرا', category:'electronics', difficulty:'easy', aliases:['كاميرا'] },
  { id:'watch', name:'ساعة', category:'electronics', difficulty:'easy', aliases:['ساعة'] },
  { id:'car', name:'سيارة', category:'vehicles', difficulty:'easy', aliases:['سيارة'] },
  { id:'bicycle', name:'دراجة', category:'vehicles', difficulty:'easy', aliases:['دراجة'] },
  { id:'airplane', name:'طائرة', category:'vehicles', difficulty:'easy', aliases:['طائرة'] },
  { id:'boat', name:'قارب', category:'vehicles', difficulty:'easy', aliases:['قارب'] },
  { id:'doctor', name:'طبيب', category:'jobs', difficulty:'easy', aliases:['طبيب'] },
  { id:'teacher', name:'معلم', category:'jobs', difficulty:'easy', aliases:['معلم'] },
  { id:'chef', name:'طاهي', category:'jobs', difficulty:'easy', aliases:['طاهي'] },
  { id:'school', name:'مدرسة', category:'places', difficulty:'easy', aliases:['مدرسة'] },
  { id:'hospital', name:'مستشفى', category:'places', difficulty:'easy', aliases:['مستشفى'] },
  { id:'beach', name:'شاطئ', category:'places', difficulty:'easy', aliases:['شاطئ'] },
  { id:'chess', name:'شطرنج', category:'games', difficulty:'easy', aliases:['شطرنج'] },
  { id:'football', name:'كرة القدم', category:'games', difficulty:'easy', aliases:['كرة'] },
  { id:'telescope', name:'تلسكوب', category:'weird', difficulty:'medium', aliases:['تلسكوب'] },
  { id:'compass', name:'بوصلة', category:'weird', difficulty:'medium', aliases:['بوصلة'] },
  { id:'rubber_duck', name:'بطة مطاطية', category:'funny', difficulty:'medium', aliases:['بطة'] }
];
